FROM multiqc/multiqc:v1.35

LABEL org.opencontainers.image.title="SurvOm MultiQC development image"
LABEL org.opencontainers.image.description="Pinned MultiQC runtime for common.qc.multiqc development validation"

RUN multiqc --version
